apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "postgres:14-alpine"
        env:
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_DB
            value: "simple_bank"
          - name: POSTGRES_PASSWORD
            value: "secret"
        ports:
          - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      name: main-port
      port: 5432
      targetPort: 5432